spring:
  application:
    name: expense-tracker

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true3

  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true
    username: root
    password: 12345

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.authentication: DEBUG
    com.angelstanchev.expense_tracker: DEBUG



---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true
    username: root
    password: 12345

